---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: system-trixieua
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: script
    scripts:
      - updates-testing.sh # Enable updates-testing

  # add repos
  - type: dnf  
    repos:
      files: 
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - bieszczaders/kernel-cachyos-addons
        - bieszczaders/kernel-cachyos-addons
        - trixieua/mutter-patched
        - trixieua/mesa-clang
        - trixieua/morewaita-icon-theme 
        - codifryed/CoolerControl
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      nonfree: rpmfusion

  - type: dnf 
    install:
      packages:
        - adw-gtk3-theme
        - bat
        - btop
        - chntpw
        - code
        - coolercontrol
        - distrobox
        - fastfetch
        - fatresize
        - gamescope
        - gnome-tweaks
        - gparted
        - htop
        - kernel-cachyos-lto
        - kernel-cachyos-lto-devel-matched
        - mangohud
        - mc
        - mock
        - mock-rpmfusion-free
        - mock-rpmfusion-nonfree
        - morewaita-icon-theme
        - ncdu
        - nvtop
        - qemu
        - rclone
        - rpmdevtools
        - rpmrebuild
        - scx-scheds
        - smartmontools
        - sshfs
        - uxplay
        - xeyes
        - zsh
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-classic-session
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra


  - type: dnf
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:trixieua:mutter-patched
        skip-unavailable: true
        packages:
          - xorg-x11-server-Xwayland
          
  - type: dnf
    replace:
    - from-repo: copr:copr.fedorainfracloud.org:trixieua:mesa-clang
      skip-unavailable: true
      packages:
        - mesa-filesystem
        - mesa-libgbm
        - mesa-dri-drivers
        - mesa-libEGL
        - mesa-libGL
        - mesa-vulkan-drivers
        - mesa-va-drivers

  - type: signing # this sets up the proper policy & signing files for signed images to work fully