---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: system-trixieua
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: script
    scripts:
      - updates-testing.sh # Enable updates-testing

  # add repos
  - type: rpm-ostree
    repos:
    - https://packages.microsoft.com/yumrepos/vscode/config.repo
    - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-lto-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/shdwchn10/zenpower3/repo/fedora-%OS_VERSION%/shdwchn10-zenpower3-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/morewaita-icon-theme/repo/fedora-%OS_VERSION%/trixieua-morewaita-icon-theme-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/tetr.io/repo/fedora-%OS_VERSION%/trixieua-tetr.io-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/mesa-clang/repo/fedora-%OS_VERSION%/trixieua-mesa-clang-fedora-%OS_VERSION%.repo?arch=x86_64
    - https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/repo/fedora-%OS_VERSION%/g3tchoo-prismlauncher-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/lizardbyte/beta/repo/fedora-%OS_VERSION%/lizardbyte-beta-fedora-%OS_VERSION%.repo

    keys:
    - https://packages.microsoft.com/keys/microsoft.asc
    install:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm


  - type: rpm-ostree

    optfix:
      - tetrio

    install:
      - adw-gtk3-theme
      - bat
      - btop
      - chntpw
      - chromium
      - code
      - coolercontrol
      - distrobox
      - fastfetch
      - gamescope
      - gnome-tweaks
      - gparted
      - htop
      - keepassxc
      - kernel-cachyos-lto
      - kernel-cachyos-lto-devel-matched
      - libva-nvidia-driver 
      - mangohud
      - mc
      - mock
      - mock-rpmfusion-free
      - mock-rpmfusion-nonfree
      - morewaita-icon-theme
      - ncdu
      - nvtop
      - prismlauncher
      - qemu
      - rpmdevtools
      - rpmrebuild
      - smartmontools
      - sshfs
      - Sunshine
      - tetrio
      - xeyes
      - zenmonitor3
      - zsh
      - https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.6.5.1/opentabletdriver-0.6.5.1-1.x86_64.rpm

    remove:
      - firefox
      - firefox-langpacks
      - gnome-classic-session
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra

  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gdm
          - gnome-shell
          - gnome-shell-common
          - xorg-x11-server-Xwayland
          
  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mesa-clang/repo/fedora-%OS_VERSION%/trixieua-mesa-clang-fedora-%OS_VERSION%.repo?arch=x86_64
        packages:
          - mesa-filesystem
          - mesa-libgbm
          - mesa-dri-drivers
          - mesa-libEGL
          - mesa-libGL
          - mesa-vulkan-drivers
          - mesa-va-drivers
  - type: signing # this sets up the proper policy & signing files for signed images to work fully