---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: system-trixieua
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: script
    scripts:
      - updates-testing.sh # Enable updates-testing

  # add repos
  - type: rpm-ostree
    repos:
    - https://packages.microsoft.com/yumrepos/vscode/config.repo
    - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-lto-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/shdwchn10/zenpower3/repo/fedora-%OS_VERSION%/shdwchn10-zenpower3-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/morewaita-icon-theme/repo/fedora-%OS_VERSION%/trixieua-morewaita-icon-theme-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/tetr.io/repo/fedora-%OS_VERSION%/trixieua-tetr.io-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
    - https://repo.librewolf.net/librewolf.repo
    keys:
    - https://packages.microsoft.com/keys/microsoft.asc
    install:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm

  # add cachyos kernel
  - type: rpm-ostree
    install:
      - kernel-cachyos-lto
      - kernel-cachyos-lto-devel-matched
    remove:
      - kernel-core
      - kernel
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
  - type: rpm-ostree
    optfix:
      - tetrio
    install:
      - adw-gtk3-theme
      - bat
      - btop
      - chntpw
      - chromium
      - code
      - coolercontrol
      - distrobox
      - fastfetch
      - gamescope
      - gnome-tweaks
      - gparted
      - htop
      - keepassxc
      - librewolf
      - libva-nvidia-driver 
      - mc
      - morewaita-icon-theme
      - ncdu
      - nvtop
      - qemu
      - rpmdevtools
      - rpmrebuild
      - smartmontools
      - tetrio
      - virt-manager
      - xeyes
      - zenmonitor3
      - zsh
      - https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.6.5.1/opentabletdriver-0.6.5.1-1.x86_64.rpm

      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gdm
          - gnome-shell
          - gsettings-desktop-schemas
          - xorg-x11-server-Xwayland

  - type: signing # this sets up the proper policy & signing files for signed images to work fully